### ISSUE TITLE
Need extra level of folder nesting in zip build

### ISSUE THREAD

**Issue by TheDuckCow** [Moo-Ack-Productions/bpy-build#4]
See the video here, which shows the user-installable build is not in the right format for manual installs, as it expands all files into the root of the addons folder:

https://youtu.be/EOJ29XR1YEQ

**Comment by TheDuckCow** [comment]
Hey @StandingPadAnimations this is still an open issue, and a blocker for merging the build system (as we can't distribute the generated zip file).

**Comment by TheDuckCow** [comment]
So, having some more thoughts about this:

**Option 1:**

- We could try to make use of the .gitattributes ignore-export ruleset as a way to indicate what should be compiled with the repo. Thus the initial step of the repo would be to run a git export which would create a zip file for the ouput.
- We would unzip this into a build folder
- Then, we could specify a list of extra folders and files to copy over (simialr to the `mcprep_dev.txt` file). This would be everything excluded by the git repo such as resources.

**Option 2:**

- Stay closer to how we have it now, whereby we specify the subfolder to generate an archive from, but then define a shutil ignore rule for what _not_ to include.
- Perhaps an easier change, and we'd configure this ruleset in the yaml build file for a given addon

**Option 3:**

- Similar to the above, exclude more restrictive in that you'd specify all files (or folders and their sub folders) to use for building. So that way if you have a rogue temp folder in your MCprep folder, it wouldn't get copied over unless you explicitly added it. 
- Thus it would also be easy to add in a "-fast" option to only optionally include or exclude the installation of the MCprep_resoruces subfodler (which we want to make as a flag option, to decide to do or not).

Curious to hear your thoughts on this.

**Comment by StandingPadAnimations** [comment]
Here's my idea (based around combing option 2 and 3):
- Replace unpacking the zip archive with just copying addon files to Blender
- Create a base `-fast` option based around modified timestamps 
- Allow adding on top of `-fast` using the config like so:
```yaml
during_build:
  default:
    - blah blah blah
  fast:
    - exclude_file("blah blah blah")
    - exclude_dir("blah blah blah")
```
where `fast` becomes a reserved case name like `default`.

**Comment by TheDuckCow** [comment]
I'm fine with this approach. Do you have time to tackle this one? I'm going to spend some time working on rewriting the test fixture. Really hoping we can get all these things together and ready for next Sunday!

**Comment by TheDuckCow** [comment]
With the latest pushes to main, this is working well - closing, thanks @StandingPadAnimations!
